name: Master Branch Build Webhook

on:
  # This trigger handles both direct pushes and merge events to the master branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: ['21']

    steps:
    - uses: actions/checkout@v4

    - name: Cache Maven wrapper
      uses: actions/cache@v4
      with:
        path: .mvn/wrapper
        key: ${{ runner.os }}-maven-wrapper-${{ hashFiles('**/maven-wrapper.properties') }}

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
        cache: 'maven'

    - name: Build with Maven
      run: ./mvnw -B clean install

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Maven Tests
        path: '**/target/surefire-reports/*.xml'
        reporter: java-junit
        fail-on-error: true

    - name: Generate JaCoCo Coverage Report (Unix)
      if: runner.os != 'Windows'
      run: ./mvnw jacoco:report

    - name: Generate JaCoCo Coverage Report (Windows)
      if: runner.os == 'Windows'
      run: .\mvnw.cmd jacoco:report

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: '**/target/site/jacoco/'

    - name: SonarCloud Analysis
      if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: ./mvnw -B verify sonar:sonar
