name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java: [ '21' ]
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: Cache Maven wrapper
      uses: actions/cache@v4
      with:
        path: .mvn/wrapper
        key: ${{ runner.os }}-maven-wrapper-${{ hashFiles('**/maven-wrapper.properties') }}

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
        cache: 'maven'

    - name: Build with Maven (Unix)
      if: runner.os != 'Windows'
      run: ./mvnw -B clean install

    - name: Build with Maven (Windows)
      if: runner.os == 'Windows'
      run: .\mvnw.cmd -B clean install

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Maven Tests
        path: '**/target/surefire-reports/*.xml'
        reporter: java-junit
        fail-on-error: true

    - name: Generate JaCoCo Coverage Report (Unix)
      if: runner.os != 'Windows'
      run: ./mvnw jacoco:report

    - name: Generate JaCoCo Coverage Report (Windows)
      if: runner.os == 'Windows'
      run: .\mvnw.cmd jacoco:report

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: '**/target/site/jacoco/'
